export const genres = {
  items: [
    { song: "pop", img: "./Pop.jpeg" },
    { song: "hip hop", img: "./hip-hop.jpeg" },
    { song: "rock", img: "./Rock.jpeg" },
    { song: "rythm and blues", img: "./R&B.jpeg" },
    { song: "soul", img: "./soul.jpeg" },
    { song: "reggae", img: "./reggae.jpeg" },
    { song: "country", img: "./Country.jpeg" },
    { song: "funk", img: "./Funk.png" },
    { song: "folk", img: "./Folk.jpeg" },
    { song: "jazz", img: "./jazz.jpeg" },
    { song: "disco", img: "./disco.jpeg" },
    { song: "classical", img: "./classical.jpeg" },
    { song: "eletronic", img: "./eletronic.jpeg" },
    { song: "blues", img: "./blues.jpeg" },
    { song: "christian music", img: "./christian.jpeg" },
    { song: "metal", img: "./metal.jpeg" },
    { song: "heavy metal", img: "./heavy_metal.jpeg" },
    { song: "punk", img: "./punk.png" },
    { song: "techno", img: "./techno.jpeg" },
    { song: "alternative rock", img: "./alternative_rock.jpeg" },
  ],
};
